### ISSUE TITLE
Clarification on concatenate_fasta Dereplication Process

### ISSUE THREAD

**Issue by vsanchez0** [BigDataBiology/SemiBin#146]
Hi, I'm currently working with the semibin2 tool and have encountered a specific query regarding the `concatenate_fasta` command. I couldn't find detailed documentation on whether `concatenate_fasta` also handles dereplication of the resulting file.

Here's my situation: I've already generated sorted BAM files using a concatenated FASTA file that I created and dereplicated without using the `semibin2 concatenate_fasta` command. Now, I'm looking to perform multisample binning, and I want to make sure I'm following the correct procedure with respect to dereplication.

Could you clarify whether `concatenate_fasta` includes dereplication in its process, or if I should manually dereplicate the concatenated FASTA file after it's generated?

**Comment by luispedro** [comment]
No, it does not perform dereplication. It only concatenates the file while adjusting the headers.

Dereplicating would actually mess up the process because you'd have to choose which sample to assign contigs to.

If you have already dereplicated and created BAM files, then I would actually advise you to treat the result as a kind of co-assembly (https://semibin.readthedocs.io/en/latest/usage/#co-assembly-binning_1) instead of the multi-sample approach.

I am going to close the issue here. For more open ended discussions, you can also use the mailing-list at:

https://groups.google.com/g/semibin-users

**Comment by tfaitova1** [comment]
Thanks, we have similar question. 
Since the assembly from different samples may have very similar or exactly the same contig, if it's not dereplicated, the reads will be mapped to the first contig in the concanated fasta, which will impact the number of reads mapping to the similar contig that belong to the other sample. 
This could impact the abundance of a contig. Will this be a problem for coverage based binning? 

Have you perhaps perfom any testing regarding the accuracy of the contig abundance?

Thank you in advance! 
Tereza
